# 프로미스

여기까지 오셨다면 여러분은 한 가지를 제외한 React.js를 다루기 위한 기본적인 자바스크립트 컨셉과 개념은 파악하셨습니다.

이번 강의는 자바스크립트 기본과 응용이 마지막 편 입니다.

자바스크립트의 비동기 처리를 돕는 `프로미스`에 대해서 배워보는 시간을 갖도록 하겠습니다.

## 01. 비동기란?

우리가 지금까지 작성해온 코드들은 작성한 순서대로 동작했습니다 아래처럼 말이죠

```javascript
console.log("1");
console.log("2");
console.log("3");
console.log("4");
```

1,2,3,4가 순서대로 출력됩니다 그 이유는 너무 당연하게도, 우리가 그런 순서대로 배치를 했기 때문이죠, 이러한 코드의 흐름을 `동기적`이라고 부릅니다.

`동기적`이라는 뜻은 이전의 작업을 마치고나서, 다음의 작업을 수행한다는 의미입니다.

그렇다면 `비동기`라는 것은 무엇일까요?

자바스크립트에는 `setTimeout`이라는 아무것도 하지 않는 기다는 특이한 함수가 있습니다.

이 `setTimeout`함수는 그 이름에서 유추할 수 있듯이, 타이머를 생성하는 함수입니다 만약 여러분이 3초 뒤에 "HELLO"를 출력하는 등의 타이머가 종료된 이후에 어떠한 동작을 실행시키고 싶다면, 이 함수를 사용하여 그런 동작을 수행할 수 있습니다.

이 함수는 일반적으로는 2개의 파라미터를 전달하여 사용하게 되는데요, 문법은 아래와 같습니다.

```javascript
setTimeout(콜백함수, 딜레이타임); // 딜레이 타임은 ms단위
```

`setTimeout` 함수는 두번째 인자로 받은 ms단위의 딜레이타임이 지난 이후, 첫번째 인자로 받은 콜백함수를 수행합니다.

그럼 아래의 예제를 통해 위에서 언급한 예시(3초 뒤에 "HELLO"를 출력한다)를 실제로 구현해보도록 하겠습니다.

```javascript
setTimeout(() => {
  console.log("HELLO");
}, 3000);

console.log("1");
console.log("2");
console.log("3");
console.log("4");
console.log("5");
```

위의 예제를 직접 CodeSandBox에 붙여넣고 실행해보세요 결과는 아래와 같습니다

```text
1
2
3
4
5
3
HELLO
```

순서대로 동작하지 않았습니다 모두 확인하셨나요? 만약 순서대로 작동했다면 3초를 기다린 후에, 모든 출력이 이루어져야 합니다.

그러나 우리는 출력 결과를 통하여 분명 `setTimeout` 함수가 먼저 호출되었지만, 그 아래있는 `console.log`함수들이 먼저 수행된 뒤 "HELLO"가 출력된것을 알 수 있습니다.

이러한 작업들을 `비동기 작업`이라고 합니다

`비동기`를 쉽게 설명하자면 아래와 같습니다

> 특정 코드의 연산이 끝나는 것을 기다리지 않고, 다음 코드를 바로 실행하는 것

그럼 이러한 `비동기`작업은 어떤 상황에서 이용하게 될까요?

가장 대표적으로 소개되는 `비동기 처리`의 사례는 API 호출 즉, 서버와의 통신입니다.

유튜브를 예로 들어보겠습니다

만약 여러분이 이용하는 유튜브의 코드가 모두 동기적으로 작동하게 되면 어떤 상황이 발생할까요?

여러분이 유튜브 첫 화면에 진입하였을 때 어떤가요? PC버전 기준으로 접속하였을 때 추천 영상들이 최소 10개 이상은 노출됩니다

추천 영상은 서버에서 데이터를 받아와야 합니다, 즉 우리가 가지고 있지 않다는 뜻이죠 이러한 영상들을 받아오기 위해 우리는 데이터를 요청하게되고, 서버는 이에 응답해 데이터를 선별해 보내주게됩니다

그런데, 이러한 통신은 변수가 많이 존재하기때문에 정확한 시간을 예상하기는 불가능합니다 즉, 얼마나 걸릴지 모른다는 것이죠

만약 유튜브가 동기적으로 동작한다면 여러분은 얼마나 걸릴지 모르는 그 추천영상 데이터를 받아보기 전까지는 하얀색 화면만 보고 있어야 합니다.

그러나 유튜브는 그렇게 동작하지 않습니다 접속과 동시에 일단 회색으로 스켈레톤(대충 배치도라고 생각하시면 됩니다)들을 보여주고 무언가 로딩되고 있다고 알려줍니다

이런 동작들은 `비동기 처리`없이는 불가능합니다.

## 02. Promise 없이 지금까지 배운대로 해보기

자 그러면 비동기에 대해 알아보았으니 우리는 이 비동기 처리를 자유 자재로 다루는 방법을 익히기만 하면 됩니다.

만약 우리가 3초 뒤에 전달한 값이 100 이상인지 판별하여 결과를 반환하는 함수가 필요하다고 가정하겠습니다.

여기서 중요한건 우리는 3초 뒤에 그 값이 100 이상인지 검사해서 결과를 반환해야 합니다.

우리가 아까 배운 `setTimeout`을 이용해서 한번 시도해볼까요?

```javascript
const isOverHunnit = (value) => {
  return setTimeout(() => {
    return value >= 100;
  }, 3000);
};

console.log(isOverHunnit(101));
```

결과는 아래와 같습니다

```
3908
```

이 결과는 무엇인가요? 우리는 분명 setTimeout 함수를 반환했고, 그 함수의 반환값으로 boolean을 설정했습니다 그런데 이 숫자는 무엇인가요?

결론적으로 말하면, setTimeout은 콜백함수의 결과값을 반환하는게 아닌, 자기 자신의 ID를 반환합니다 즉 타이머 식별자를 반환한다는 것이죠 우리는 나중에 이 ID를 통해 동작하는 타이머를 취소할 수도 있습니다만 현재 우리가 원하는 값은 아닙니다.

그럼 어떻게 해결해야 할까요??

## 03. Promise

### 3-1. Promise란?

오늘 배울 `Promise`는 자바스크립트의 비동기처리를 돕는 객체로써, 이런 자바스크립트의 비동기 처리의 결과를 받아볼 수 있도록 도와줍니다.

`Promise`는 다음과 같이 만들 수 있습니다.

```javascript
const func = new Promise(executer); // <- executer는 함수입니다.
```

`Promise` 객체는 `new` 키워드와 생성자를 이용하여 생성하여야 합니다.

이때 생성자는 실행함수인 `executer` 함수를 파라미터로 전달받습니다 이 함수를 통해 우리는 `비동기 처리`를 할 수 있게 됩니다.

그럼 이 `executer`함수를 살펴보도록 하겠습니다.

아래는 `executer` 함수를 구현한 예제입니다.

```javascript
const executer = (resolve, reject) => {
  // your logic is here
};
const func = new Promise(executer);
```

비동기 처리는 실패할 수도 있습니다 따라서 `Promise`객체의 실행함수인 `executer`는 비동기 처리가 성공했을 때와 실패했을때의 응답을 각각 설정할 수 있습니다.

`executer`는 두개의 함수 파라미터 `resolve`와 `reject`를 받게되며, `Promise`객체에 의해 즉시 실행됩니다.

이 `resolve & reject`는 각각 아래와 같은 역할을 담당하게 됩니다.

1. resolve(함수) : 비동기 처리가 성공적으로 수행되었을 때 결과값을 반환하는 역할

2. reject(함수) : 비동기 처리가 실패하였을 때 결과값 또는 에러를 반환하는 역할 (보통 오류의 원인을 반환합니다)

그럼 `Promise`객체와 실행함수 `executer`의 성공시에 호출하는 함수 파라미터 `resolve`를 이용하여 비동기처리가 성공했다고 가정하고, 숫자 3000을 반환해보도록 하겠습니다.

```javascript
const executer = (resolve, reject) => {
  resolve(3000);
};
const func = new Promise(executer);
console.log(func);
```

위 예제코드의 결과는 아래와 같습니다.

```javascript
Promise {<pending>}
```

무언가 이상합니다 우리는 `executer`에서 분명 `resolve`를 통해 3000을 반환해줬습니다. 그러므로 우리가 원하는 반환값은 숫자 3000입니다.

그런데 결과는 그냥 `Promise` 객체로 전달됩니다 이건 어떻게 된 일일까요?

### 3-2. Promise 실행함수의 결과값을 받아보기

> 문법이 조금 어색할 수 있지만 조금만 더 해보세요 ! 금방 익숙해질겁니다.

`Promise`객체는 `then` 그리고 `catch`메서드를 이용하여 결과값을 전달받을 수 있습니다 즉, `Promise`객체를 담은 변수 자체가 결과값이 아니라는 뜻 입니다.

그럼 `then`을 이용하여 위 예제 코드를 올바르게 고쳐보도록 하겠습니다.

```javascript
const executer = (resolve, reject) => {
  resolve(3000);
};
const func = new Promise(executer);
func.then((value) => {
  console.log(value); // 3000 출력
});
```

성공적으로 3000이 출력되었나요? 이렇게 `then`메서드를 이용하면, `Promise`의 `resolve` 결과 즉 성공했을때의 결과를 콜백함수의 파라미터로 받아 접근할 수 있게 됩니다.

이번에는 실패 했을때의 결과값을 반환하는 `reject`함수를 이용하여 실패를 반환하고, `Promise`객체의 `catch` 메서드를 이용하여 실패를 받아보도록 하겠습니다.

```javascript
const executer = (resolve, reject) => {
  reject("ERROR!!");
};
const func = new Promise(executer);
func
  .then((value) => {
    console.log(value);
  })
  .catch((err) => {
    console.log(err); // ERROR!! 출력
  });
```

"ERROR!!"가 잘 출력되었나요?

이번에는 실행함수에서 의도적으로 `reject`를 통하여 실패를 반환해 보았습니다.

실습해본 것 처럼 `then`은 성공했을때의 결과값을 `catch`는 실패했을때의 결과값을 받아옵니다.

그럼 `resolve`와 `reject`를 둘다 쓰면 어떻게 될까요?

아래는 `resolve`와 `reject`를 둘다 사용한 예제입니다.

```javascript
const executer = (resolve, reject) => {
  resolve("SUCCESS!!");
  reject("ERROR!!");
};
const func = new Promise(executer);
func
  .then((value) => {
    console.log(value); // SUCCESS!! 출력
  })
  .catch((err) => {
    console.log(err);
  });
```

`resolve`에서 전달된 결과값은 출력되지만 `reject`는 이루어지지 않습니다 이것은 왜 그런것일까요?

### 3-3. Promise의 상태 이해하기

`Promise`는 아래 세가지 중 하나의 상태를 가집니다

1. 대기(pending): 작업이 아직 종료되지 않았거나, 무언가 문제가 발생했을때 (오류)
2. 이행(fulfilled): 작업이 성공함
3. 거부(rejected): 작업이 실패함.

![](https://mdn.mozillademos.org/files/8633/promises.png)

> 출처 MDN : promise 설명 이미지

위 `Promise`의 상태와 동작방식을 나타내는 사진 자료를 보면, 이미 작업이 수행되어 `then`이나 `catch`가 수행된 `Promise`객체는 실행을 멈추는 것을 알 수 있습니다.

즉, `Promise`는 `resolve`나, `reject`를 한번 이상 호출한 뒤에는 추가적인 결과를 반환하지 않습니다.

### 3-4. 진짜 비동기 작업을 Promise로 처리하기

위에서 `Promise`를 통해 결과값을 받아보긴 했지만 아직 비동기 함수의 처리 결과를 받아본건 아닙니다.

우리가 위에서 사용해보았던 첫번째 비동기 함수인 `setTimeout`의 결과값을 `Promise`를 통해 받아보겠습니다

아래는 위에서 `Promise`없이 시도해본, 3초 뒤에 전달한 값이 100 이상인지 판별하여 결과를 반환하는 함수를 `Promise`를 사용하여 구현해본 예제입니다.

```javascript
const isOverHunnit = (value) => {
  return new Promise((resolve, reject) =>
    setTimeout(() => {
      resolve(value >= 100);
    }, 3000)
  );
};

isOverHunnit(99).then((value) => {
  console.log(value); // false
});
isOverHunnit(101).then((value) => {
  console.log(value); // true
});
```

> 정답 코드를 보기 전에 한번 스스로 구현해보세요

`isOverHunnit`이 이제는 `Promise`를 반환합니다.

이 `Promise`의 `then`을 통하여 우리는 `resolve`를 통해 전달받은 값을 이용할 수 있습니다.

이번엔 한번 더 업그레이드해서, number 타입이 아닌 값을 전달하면 `reject`를 호출하여 오류를 반환하는 예제를 해보도록 하겠습니다.

```javascript
const isOverHunnit = (value) => {
  return new Promise((resolve, reject) =>
    setTimeout(() => {
      if (typeof value === "number") resolve(value >= 100);
      else reject("오류 : number 타입 값을 전달하지 않았습니다");
    }, 3000)
  );
};

isOverHunnit("99")
  .then((value) => {
    console.log(value);
  })
  .catch((err) => {
    console.log(err); // 오류 : number 타입 값을 전달하지 않았습니다
  });

isOverHunnit(101)
  .then((value) => {
    console.log(value); // true
  })
  .catch((err) => {
    console.log(err);
  });
```

위 예제가 잘 실행되었나요?

`catch`와 `reject`까지 이용해 보았습니다.
